# Nameless Plugin configuration

# API URL
# This needs to be the full API URL, including API key
# For example http://yoursite.com/api/v1/API_KEY
api-url: ""

# Use reports?
# If true, a /report command will be added to report users ingame
# which will be added to the website's report system
# Valid values = true, false
enable-reports: true

# Enable join notifications?
# If true, players will be sent a notification message
# on join, containing the amount of alerts and private
# messages received
# Valid values = true, false
join-notifications: true