name: NamelessMC
main: com.namelessmc.namelessplugin.NamelessPlugin
website: https://namelessmc.com/
version: 0.1
commands:
  register:
    description: Register for an account on the website
    usage: /register email
  getuser:
    description: get a user from the web
    usage: /getuser username/uuid
softdepend: [Vault]
