name: NamelessMC
main: com.namelessmc.namelessplugin.spigot.NamelessPlugin
authors: [Samerton, IsS127]
website: https://namelessmc.com/
version: 0.1
commands:
  register:
    description: Register for an account on the website
    usage: /register email
  getuser:
    description: Get information about a specified user
    usage: /getuser username
  report:
    description: Report a user
    usage: /report username reason
softdepend: [Vault]
