name: NamelessMC
main: com.namelessmc.spigot.NamelessPlugin
author: Derkades
authors: [Derkades, Samerton, IsS127]
website: https://plugin.namelessmc.com/
version: '@project.version@'

softdepend: [Vault, PlaceholderAPI]

commands:
  namelessplugin:
    description: NamelessMC plugin command (/nlpl also works)
    aliases: [namelessmcplugin, nlmcpl, nlpl]