# Nameless Plugin configuration

# For example http://yoursite.com/api/v2/API_KEY
# Enable the API and obtain the API URL in AdminCP > Core > API
api-url: ""

# Enter this if you wish for the plugin to send data about this server
# and its players to the website. This is required for name and rank sync.
# You can find this in AdminCP -> Minecraft -> Minecraft Servers
server-id: 0

# This feature sends information about the server and online players to
# your NamelessMC website. This value is in seconds. Increase to lower
# the frequency that data is sent. Decrease to send data more frequently.
# Setting this too low can cause lag. Set to 0 to disable.
server-data-upload-rate: 10

# Enable PlaceholderAPI and MVdWPlaceholderAPI placeholders
# This will increase traffic to your NamelessMC website (depending on placeholders-request-delay)
# This option will be ignored if PlaceholderAPI and MVdWPlaceholderAPI are not installed
enable-placeholders: false

# Number of milliseconds in between notifications request
# Lower number means more frequent updates of placeholders, but higher
# network usage.
placeholders-request-delay: 2000

# Turn on debug mode for the underlying NamelessMC Java API
api-debug-mode: false

# Send a message to players that don't have a NamelessMC account when they join
not-registered-join-message: false
