name: NamelessMC
main: com.namelessmc.plugin.NamelessSpigot.NamelessPlugin
authors: [Samerton, IsS127, Lmmb74]
website: https://namelessmc.com/
version: Pre-2
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI]
commands:
  nameless:
    description: Has reload command.
    aliases: [nmc, namelessmc, nl]