name: NamelessMC
main: com.namelessmc.plugin.NamelessSpigot.NamelessPlugin
authors: [Samerton, IsS127, Derkades]
website: https://plugin.namelessmc.com/
version: '@project.version@'
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI]
commands:
  namelessplugin:
    description: NamelessMC plugin command (/nlpl also works)
    aliases: [namelessmcplugin, nlmcpl, nlpl]