name: NamelessMC
main: com.namelessmc.plugin.NamelessSpigot.NamelessPlugin
authors: [Samerton, IsS127, Lmmb74]
website: https://plugin.namelessmc.com/
version: '@project.version@'
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI]
commands:
  nameless:
    description: Has reload command.
    aliases: [nmc, namelessmc, nl]