name: NamelessMC
main: com.namelessmc.namelessplugin.spigot.NamelessPlugin
authors: [Samerton, IsS127, Lmmb74]
website: https://namelessmc.com/
version: Pre-1.1.1
softdepend: [Vault,PlaceholderAPI,MVdWPlaceholderAPI]