name: NamelessMC
main: com.namelessmc.plugin.oldbukkit.OldBukkitNamelessPlugin
author: Derkades
website: https://plugin.namelessmc.com/
version: '@project.version@'
softdepend: [Vault, PlaceholderAPI, Maintenance, LuckPerms]
