name: NamelessMC
main: com.namelessmc.plugin.paper.PaperNamelessPlugin
author: Derkades
website: https://plugin.namelessmc.com/
version: '@project.version@'
api-version: 1.18
softdepend: [Vault, PlaceholderAPI, Maintenance, LuckPerms]
